#!/bin/bash

# Arguments passed by ./runalg:
# $1 : Left Image (im0.png)
# $2 : Right Image (im1.png)
# $3 : Number of Disparities (ndisp)
# $4 : Output Directory

# Check arguments
if [ "$#" -ne 4 ]; then
    echo "usage: run <im0.png> <im1.png> <ndisp> <outdir>"
    exit 1
fi

IM0="$1"
IM1="$2"
NDISP="$3"
OUTDIR="$4"

# Call your Python script.
# We map the positional arguments to your named flags.
python3 alg-S2M2/run_middlebury.py \
    --img_left "$IM0" \
    --img_right "$IM1" \
    --num_disparities "$NDISP" \
    --output_dir "$OUTDIR"
